### ISSUE TITLE
Problems while running sequencer-train, sequencer-test and sequencer-predict on docker

### ISSUE THREAD

**Issue by brash6** [KTH/chai#11]
Hello, 

I've built SequenceR from source on a docker image (not from docker hub) and I encounter these issues : 

- sequencer-train : 
```
sequencer-train.sh start
Starting data preprocessing
Please backup existing pt files: /SequenceR/data/final.train*.pt, to avoid overwriting them!
Starting training
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=33 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/SequenceR/src/lib/OpenNMT-py/onmt/train_single.py", line 90, in main
    opt = training_opt_postprocessing(opt, device_id)
  File "/SequenceR/src/lib/OpenNMT-py/onmt/train_single.py", line 81, in training_opt_postprocessing
    torch.cuda.set_device(device_id)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/torch/csrc/cuda/Module.cpp:33
```
Maybe it is because I have a GPU on my computer without the drivers to train on it as it's a powerless GPU. Hence, I would like to run on CPUs but I don't know how.

- sequencer-test : 
```
sequencer-test.sh start
Starting test data translation
Traceback (most recent call last):
  File "translate.py", line 5, in <module>
    import configargparse
ImportError: No module named configargparse
sequencer-test.sh done
```
It is strange since it should have been installed during the docker installation as it is in the OpenNMT-py requirements.

- sequencer-predict : 
```
sequencer-predict.sh start
Input parameter:
BUGGY_FILE_PATH = /SequenceR/1.java
BUGGY_LINE = 609
BEAM_SIZE = 3
OUTPUT = /SequenceR

Creating temporary working folder

Abstracting the source file

Tokenizing the abstraction

Truncate the abstraction to 1000 tokens

Generating predictions
./sequencer-predict.sh: line 116:   182 Killed                  python3 $CURRENT_DIR/lib/OpenNMT-py/translate.py -model $ROOT_DIR/model/model.pt -src $CURRENT_DIR/tmp/${BUGGY_FILE_BASENAME}_abstract_tokenized_truncated.txt -output $CURRENT_DIR/tmp/predictions.txt -beam_size $BEAM_SIZE -n_best $BEAM_SIZE > /dev/null

Post process predictions
All predictions contains <unk> tokenPost process generates none valid predictions
```
I tried to increase the RAM allocated to docker to 4GB but it didn't change anything. 

Thank you very much for this interesting project. I'm actually doing my master's thesis on Seq2Seq models for Program Repair and I'm looking forward to play with SequenceR and to understand deeper how it works.

**Comment by chenzimin** [comment]
I will try to reproduce these errors, the first one seems like a driver issue. The second and third one seems weird, will update you once I have the result.

**Comment by brash6** [comment]
Thank you ! I'll try to install CUDA and cuDNN and retry !

**Comment by brash6** [comment]
Hi, I've installed CUDA 10.2 and cuDNN and rebuilt Sequencer docker image and still have the same error for sequencer-train.sh : 
```
sequencer-train.sh start
Starting data preprocessing
[2020-04-02 16:46:34,293 INFO] Extracting features...
[2020-04-02 16:46:34,296 INFO]  * number of source features: 0.
[2020-04-02 16:46:34,296 INFO]  * number of target features: 0.
[2020-04-02 16:46:34,296 INFO] Building `Fields` object...
[2020-04-02 16:46:34,296 INFO] Building & saving training data...
[2020-04-02 16:46:34,296 INFO] Reading source and target files: /SequenceR/data/src-train.txt /SequenceR/data/tgt-train.txt.
[2020-04-02 16:46:36,049 INFO] Building shard 0.
[2020-04-02 16:47:26,614 INFO]  * saving 0th train data shard to /SequenceR/data/final.train.0.pt.

[2020-04-02 16:48:06,013 INFO] Building & saving validation data...
[2020-04-02 16:48:06,013 INFO] Reading source and target files: /SequenceR/data/src-val.txt /SequenceR/data/tgt-val.txt.
[2020-04-02 16:48:06,593 INFO] Building shard 0.
[2020-04-02 16:48:09,495 INFO]  * saving 0th valid data shard to /SequenceR/data/final.valid.0.pt.
[2020-04-02 16:48:11,685 INFO] Building & saving vocabulary...
[2020-04-02 16:48:18,981 INFO]  * reloading /SequenceR/data/final.train.0.pt.
[2020-04-02 16:48:21,771 INFO]  * tgt vocab size: 1004.
[2020-04-02 16:48:22,985 INFO]  * src vocab size: 1002.
[2020-04-02 16:48:22,985 INFO]  * merging src and tgt vocab...
[2020-04-02 16:48:25,418 INFO]  * merged vocab size: 1004.
Starting training
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=33 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/SequenceR/src/lib/OpenNMT-py/onmt/train_single.py", line 90, in main
    opt = training_opt_postprocessing(opt, device_id)
  File "/SequenceR/src/lib/OpenNMT-py/onmt/train_single.py", line 81, in training_opt_postprocessing
    torch.cuda.set_device(device_id)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/torch/csrc/cuda/Module.cpp:33
sequencer-train.sh done
```

**Comment by chenzimin** [comment]
Have you tried this? https://stackoverflow.com/a/55351774

**Comment by brash6** [comment]
I've just checked and it seems ok : 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.74       Driver Version: 442.74       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M2000M      WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   38C    P8    N/A /  N/A |    452MiB /  4096MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
```

But inside the docker image, I can't run `nvcc --version`. Is it normal or I should be able to run it inside the docker image ?

**Comment by brash6** [comment]
Also I've noticed that the ImportError of configargparse was due to a python version problem. In fact, inside the docker image, python runs `python` 2.7 and `python3` runs python 3.6. 
Hence, I've changed python command to python3 command in every shell script that was involved in the execution of sequence-test. 
Now I have the same error I have with sequencer-predict : the execution is killed. 
I've tried to allocate more memory to docker : 9GB and I still have this error. (I can't allocate more memory, I tried and docker had to reset)

**Comment by chenzimin** [comment]
> But inside the docker image, I can't run nvcc --version. Is it normal or I should be able to run it inside the docker image?
Using GPUs inside docker might be tricky, you might like to take a look at https://github.com/NVIDIA/nvidia-docker. If you would like to train a new model, doing it without might be easier, you should just need to run `setup_env.sh`

> Now I have the same error I have with sequencer-predict : the execution is killed.
Can you remove ` > /dev/null`  from `python3 $CURRENT_DIR/lib/OpenNMT-py/translate.py -model $ROOT_DIR/model/model.pt -src $CURRENT_DIR/tmp/${BUGGY_FILE_BASENAME}_abstract_tokenized_truncated.txt -output $CURRENT_DIR/tmp/predictions.txt -beam_size $BEAM_SIZE -n_best $BEAM_SIZE > /dev/null` and rerun it, so that we can see the error message?

**Comment by brash6** [comment]
I'm on windows so it's more convenient to use docker image but I should try soon to run it on a linux machine. 

I modified sequencer-predict.sh as you suggested and now I still get the same error : 
```
sequencer-predict.sh start
Input parameter:
BUGGY_FILE_PATH = /SequenceR/data/1.java
BUGGY_LINE = 609
BEAM_SIZE = 3
OUTPUT = /SequenceR

Creating temporary working folder

Abstracting the source file

Tokenizing the abstraction

Truncate the abstraction to 1000 tokens

Generating predictions
./sequencer-predict.sh: line 116:    79 Killed                  python3 $CURRENT_DIR/lib/OpenNMT-py/translate.py -model $ROOT_DIR/model/model.pt -src $CURRENT_DIR/tmp/${BUGGY_FILE_BASENAME}_abstract_tokenized_truncated.txt -output $CURRENT_DIR/tmp/predictions.txt -beam_size $BEAM_SIZE -n_best $BEAM_SIZE

Post process predictions
All predictions contains <unk> tokenPost process generates none valid predictions
```

**Comment by brash6** [comment]
I've tried to run the scripts on a linux environment ang I get these errors : 

- sequencer-train : Same error than docker image on windows 
- sequencer-test : 
```
sequencer-test.sh start
Starting test data translation
Traceback (most recent call last):
  File "translate.py", line 35, in <module>
    main(opt)
  File "translate.py", line 14, in main
    translator = build_translator(opt, report_score=True)
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/onmt/translate/translator.py", line 35, in build_translator
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/onmt/model_builder.py", line 150, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/u/users/hma11/.conda/envs/rnddatascienceenv/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/u/users/hma11/.conda/envs/rnddatascienceenv/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
sequencer-test.sh done
```
- sequencer-predict : 
```
sequencer-predict.sh start
Input parameter:
BUGGY_FILE_PATH = /home/users/hma11/SequenceR/chai/data/tmp/1.java
BUGGY_LINE = 609
BEAM_SIZE = 3
OUTPUT = /home/users/hma11/SequenceR

Creating temporary working folder

Abstracting the source file

Tokenizing the abstraction

Truncate the abstraction to 1000 tokens

Generating predictions
Traceback (most recent call last):
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/translate.py", line 35, in <module>
    main(opt)
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/translate.py", line 14, in main
    translator = build_translator(opt, report_score=True)
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/onmt/translate/translator.py", line 35, in build_translator
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
  File "/home/users/hma11/SequenceR/chai/src/lib/OpenNMT-py/onmt/model_builder.py", line 150, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/u/users/hma11/.conda/envs/rnddatascienceenv/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/u/users/hma11/.conda/envs/rnddatascienceenv/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Post process predictions
All predictions contains <unk> tokenPost process generates none valid predictions
```
Maybe theses errors are the same that occured on the docker image.

**Comment by chenzimin** [comment]
Did you install git-lfs?

**Comment by brash6** [comment]
Thank you very much, this was the problem for `sequencer-test.sh` and `sequencer-predict.sh`.
I still have the CUDA driver version problem for `sequencer-train.sh`, is it possible to run it on CPU ?

**Comment by chenzimin** [comment]
You can remove the `-gpu_ranks 0` option from `data/train.sh`

**Comment by brash6** [comment]
Thank you very much for your help, it works on CPU, both on docker and linux. 
Now I'm waiting for a GPU machine to configure it.
