### ISSUE TITLE
error in training 

### ISSUE THREAD

**Issue by kevinGit777** [KTH/chai#30]
hi, I have trouble using src/sequencer-train.sh

### FULL ERROR OUTPUT
sequencer-train.sh start
Starting data preprocessing
Please backup existing pt files: /home/hxw170013/APR/chai/results/Golden/final.train*.pt, to avoid overwriting them!
Starting training
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/home/hxw170013/APR/chai/src/lib/OpenNMT-py/onmt/train_single.py", line 114, in main
    first_dataset = torch.load(glob.glob(opt.data + '.train*.pt')[0])
  File "/home/hxw170013/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hxw170013/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
sequencer-train.sh done

I think it might because of the outdated value in version of chai/results/Golden/final.train.0.pt. But I am not sure, Can you help me out on this? Thank you!

**Comment by kevinGit777** [comment]
I also notice that my final.train.0.pt. is different than the one in your repository, any reason that could happen? This is my final.train.0.pt looks like:
`version https://git-lfs.github.com/spec/v1
oid sha256:211527bbb96082da15f55556e5c8de408a1ea18ca09e3e7e5bd581b3403f8259
size 357618988
`

**Comment by Anurag-Swarnim-Yadav** [comment]
@kevinGit777 Install git lfs.

**Comment by DongH2022** [comment]
I have the same problem during the training. Can you tell me how to solve it in detail?
